'use client';

import React, { useState } from 'react';
import { motion } from 'framer-motion';
import {
  Award,
  BookOpen,
  ChevronRight,
  Download,
  ExternalLink,
  Search,
  Target,
  DollarSign,
  Users,
  Star,
  Sparkles,
  Info,
  ChevronDown,
  ChevronUp,
} from 'lucide-react';
import { MainLayout } from '@/components/layout/MainLayout';
import { cn } from '@/lib/utils';

interface FAQItem {
  question: string;
  answer: string;
}

const rankRequirements = [
  {
    rank: 'Executive',
    color: 'bg-slate-100 text-slate-700',
    requirements: [
      { name: 'Personal Sales Volume', value: '100 PSV' },
      { name: 'Group Sales Volume', value: '500 GSV' },
    ],
    benefits: ['5% Commission', 'Wholesale Pricing'],
  },
  {
    rank: 'Silver',
    color: 'bg-gray-200 text-gray-700',
    requirements: [
      { name: 'Personal Sales Volume', value: '100 PSV' },
      { name: 'Group Sales Volume', value: '3,000 GSV' },
      { name: 'Active Executives', value: '2' },
    ],
    benefits: ['10% Commission', 'Leadership Bonus Pool'],
  },
  {
    rank: 'Gold',
    color: 'bg-amber-100 text-amber-700',
    requirements: [
      { name: 'Personal Sales Volume', value: '100 PSV' },
      { name: 'Group Sales Volume', value: '10,000 GSV' },
      { name: 'Active Silvers', value: '2' },
    ],
    benefits: ['15% Commission', 'Gold Bonus', 'Trip Qualification'],
  },
  {
    rank: 'Lapis',
    color: 'bg-blue-100 text-blue-700',
    requirements: [
      { name: 'Personal Sales Volume', value: '100 PSV' },
      { name: 'Group Sales Volume', value: '25,000 GSV' },
      { name: 'Active Golds', value: '2' },
    ],
    benefits: ['18% Commission', 'Lapis Bonus', 'Executive Trip'],
  },
  {
    rank: 'Ruby',
    color: 'bg-red-100 text-red-700',
    requirements: [
      { name: 'Personal Sales Volume', value: '100 PSV' },
      { name: 'Group Sales Volume', value: '50,000 GSV' },
      { name: 'Active Lapis', value: '2' },
    ],
    benefits: ['20% Commission', 'Ruby Bonus', 'Leadership Retreat'],
  },
];

const faqs: FAQItem[] = [
  {
    question: 'How is my commission calculated?',
    answer: 'Your commission is calculated based on your rank level and the total Group Sales Volume (GSV) generated by your organization. Base commissions range from 5% at Executive level to 25% at Diamond level, with additional bonuses available through the Leadership Development Bonus and other incentive programs.',
  },
  {
    question: 'What counts towards my Personal Sales Volume (PSV)?',
    answer: 'Personal Sales Volume includes all products you personally purchase at wholesale prices, as well as products purchased by your retail customers. Subscription orders (ADR) count towards your monthly PSV and provide consistent volume.',
  },
  {
    question: 'How do I maintain my rank qualification?',
    answer: 'To maintain your rank, you must meet the minimum requirements for 3 out of 6 consecutive months. If you fall below requirements, you have a 3-month grace period to requalify before being demoted.',
  },
  {
    question: 'What is the Leadership Development Bonus?',
    answer: 'The Leadership Development Bonus rewards you for developing leaders in your organization. You earn additional bonuses when your personally enrolled Brand Affiliates achieve new rank advancements, encouraging team growth and development.',
  },
  {
    question: 'How do subscription (ADR) bonuses work?',
    answer: 'Automatic Delivery Rewards (ADR) generate consistent volume and additional bonuses. You earn 5% ADR bonus on personal subscriptions and up to 15% on team ADR volume, creating a stable recurring income stream.',
  },
];

export default function SPPPage() {
  const [searchQuery, setSearchQuery] = useState('');
  const [expandedFAQ, setExpandedFAQ] = useState<number | null>(null);
  const [selectedRank, setSelectedRank] = useState<string | null>(null);

  const filteredFAQs = faqs.filter(
    (faq) =>
      faq.question.toLowerCase().includes(searchQuery.toLowerCase()) ||
      faq.answer.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <MainLayout>
      <div className="space-y-6">
        {/* Header */}
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
          <motion.div
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
          >
            <h1 className="text-2xl font-display font-bold text-gray-900">
              Sales Performance Plan (SPP)
            </h1>
            <p className="text-gray-600 mt-1">
              Understanding your compensation and growth path
            </p>
          </motion.div>

          <motion.a
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            href="https://www.nuskin.com/content/dam/office/pacific_new/shared/en/legal/PAC%20New%20SPP%20March%202025%20v2%20280125.pdf"
            target="_blank"
            rel="noopener noreferrer"
            className="btn-primary flex items-center gap-2"
          >
            <Download className="w-5 h-5" />
            Download Full SPP
            <ExternalLink className="w-4 h-4" />
          </motion.a>
        </div>

        {/* Quick Stats */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="grid grid-cols-1 md:grid-cols-4 gap-4"
        >
          {[
            { icon: Target, label: 'Rank Levels', value: '8', color: 'text-nuskin-primary' },
            { icon: DollarSign, label: 'Max Commission', value: '25%', color: 'text-green-600' },
            { icon: Users, label: 'Bonus Programs', value: '6+', color: 'text-purple-600' },
            { icon: Star, label: 'Trip Incentives', value: '4/year', color: 'text-amber-600' },
          ].map((stat, index) => (
            <div key={stat.label} className="card p-4 flex items-center gap-4">
              <div className={cn('p-3 rounded-xl bg-gray-100', stat.color)}>
                <stat.icon className="w-6 h-6" />
              </div>
              <div>
                <p className="text-2xl font-bold text-gray-900">{stat.value}</p>
                <p className="text-sm text-gray-500">{stat.label}</p>
              </div>
            </div>
          ))}
        </motion.div>

        {/* Rank Structure */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="card p-6"
        >
          <div className="flex items-center gap-3 mb-6">
            <div className="p-2 rounded-xl bg-gradient-to-br from-nuskin-gold/20 to-nuskin-gold/10">
              <Award className="w-5 h-5 text-nuskin-gold" />
            </div>
            <div>
              <h3 className="font-semibold text-gray-900">Rank Structure</h3>
              <p className="text-sm text-gray-500">Requirements and benefits by rank</p>
            </div>
          </div>

          <div className="space-y-4">
            {rankRequirements.map((rank, index) => (
              <motion.div
                key={rank.rank}
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: index * 0.05 }}
                className={cn(
                  'border rounded-xl overflow-hidden transition-all',
                  selectedRank === rank.rank ? 'border-nuskin-accent shadow-lg' : 'border-gray-100'
                )}
              >
                <button
                  onClick={() => setSelectedRank(selectedRank === rank.rank ? null : rank.rank)}
                  className="w-full p-4 flex items-center justify-between hover:bg-gray-50 transition-colors"
                >
                  <div className="flex items-center gap-4">
                    <span className={cn('px-4 py-2 rounded-xl font-medium', rank.color)}>
                      {rank.rank}
                    </span>
                    <div className="hidden md:flex items-center gap-4 text-sm text-gray-500">
                      {rank.requirements.slice(0, 2).map((req) => (
                        <span key={req.name}>{req.name}: <strong className="text-gray-900">{req.value}</strong></span>
                      ))}
                    </div>
                  </div>
                  {selectedRank === rank.rank ? (
                    <ChevronUp className="w-5 h-5 text-gray-400" />
                  ) : (
                    <ChevronDown className="w-5 h-5 text-gray-400" />
                  )}
                </button>

                {selectedRank === rank.rank && (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: 'auto', opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    className="px-4 pb-4 border-t border-gray-100"
                  >
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pt-4">
                      <div>
                        <h4 className="font-medium text-gray-900 mb-3">Requirements</h4>
                        <ul className="space-y-2">
                          {rank.requirements.map((req) => (
                            <li key={req.name} className="flex items-center justify-between text-sm">
                              <span className="text-gray-600">{req.name}</span>
                              <span className="font-medium text-gray-900">{req.value}</span>
                            </li>
                          ))}
                        </ul>
                      </div>
                      <div>
                        <h4 className="font-medium text-gray-900 mb-3">Benefits</h4>
                        <ul className="space-y-2">
                          {rank.benefits.map((benefit) => (
                            <li key={benefit} className="flex items-center gap-2 text-sm">
                              <Star className="w-4 h-4 text-nuskin-gold" />
                              <span className="text-gray-700">{benefit}</span>
                            </li>
                          ))}
                        </ul>
                      </div>
                    </div>
                  </motion.div>
                )}
              </motion.div>
            ))}
          </div>
        </motion.div>

        {/* FAQ Section */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
          className="card p-6"
        >
          <div className="flex items-center justify-between mb-6">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-xl bg-blue-100">
                <BookOpen className="w-5 h-5 text-blue-600" />
              </div>
              <div>
                <h3 className="font-semibold text-gray-900">Frequently Asked Questions</h3>
                <p className="text-sm text-gray-500">Common questions about the SPP</p>
              </div>
            </div>

            <div className="relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
              <input
                type="text"
                placeholder="Search FAQs..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="pl-9 pr-4 py-2 rounded-xl border border-gray-200 text-sm focus:border-nuskin-accent focus:ring-2 focus:ring-nuskin-accent/20 outline-none w-64"
              />
            </div>
          </div>

          <div className="space-y-3">
            {filteredFAQs.map((faq, index) => (
              <div
                key={index}
                className="border border-gray-100 rounded-xl overflow-hidden"
              >
                <button
                  onClick={() => setExpandedFAQ(expandedFAQ === index ? null : index)}
                  className="w-full p-4 flex items-center justify-between text-left hover:bg-gray-50 transition-colors"
                >
                  <span className="font-medium text-gray-900 pr-4">{faq.question}</span>
                  {expandedFAQ === index ? (
                    <ChevronUp className="w-5 h-5 text-gray-400 flex-shrink-0" />
                  ) : (
                    <ChevronDown className="w-5 h-5 text-gray-400 flex-shrink-0" />
                  )}
                </button>
                {expandedFAQ === index && (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: 'auto', opacity: 1 }}
                    className="px-4 pb-4"
                  >
                    <p className="text-gray-600 text-sm leading-relaxed">{faq.answer}</p>
                  </motion.div>
                )}
              </div>
            ))}
          </div>
        </motion.div>

        {/* Ask AI Banner */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3 }}
          className="bg-gradient-to-r from-nuskin-primary via-nuskin-secondary to-nuskin-accent rounded-2xl p-6 text-white"
        >
          <div className="flex items-center gap-6">
            <div className="p-4 rounded-2xl bg-white/20 backdrop-blur-sm">
              <Sparkles className="w-8 h-8" />
            </div>
            <div className="flex-1">
              <h3 className="text-xl font-bold mb-1">Have Questions About the SPP?</h3>
              <p className="text-white/80">
                Ask Stela AI for personalized explanations and how the SPP applies to your specific situation.
              </p>
            </div>
            <a
              href="/chat"
              className="px-6 py-3 bg-white text-nuskin-primary rounded-xl font-medium hover:bg-white/90 transition-colors flex items-center gap-2"
            >
              Ask Stela AI
              <ChevronRight className="w-4 h-4" />
            </a>
          </div>
        </motion.div>

        {/* Disclaimer */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.4 }}
          className="flex items-start gap-3 p-4 rounded-xl bg-gray-50 border border-gray-200"
        >
          <Info className="w-5 h-5 text-gray-400 flex-shrink-0 mt-0.5" />
          <p className="text-sm text-gray-500">
            This page provides a summary of the Sales Performance Plan. For complete details and official
            terms, please refer to the{' '}
            <a
              href="https://www.nuskin.com/content/dam/office/pacific_new/shared/en/legal/PAC%20New%20SPP%20March%202025%20v2%20280125.pdf"
              target="_blank"
              rel="noopener noreferrer"
              className="text-nuskin-primary hover:underline"
            >
              official SPP document
            </a>
            . Terms and conditions may vary by region.
          </p>
        </motion.div>
      </div>
    </MainLayout>
  );
}

